### ISSUE TITLE
Not working on my Mac!

### ISSUE THREAD

**Issue by hanoisteve** [vagababov/prime-server#1]
coffee:prime-server Steven$ ko apply -f ./grpc-service.yaml
2019/07/03 15:10:24 Error enumerating files: lstat ./grpc-service.yaml: no such file or directory
coffee:prime-server Steven$ error: no objects passed to apply
ls
Gopkg.lock		README.md		http_service.yaml	main.go			prime_api_simple.yaml	script.sh
Gopkg.toml		client			http_service2.yaml	prime.go		prime_server.go		vendor
LICENSE			grpc_service.yaml	http_service3.yaml	prime_api.yaml		proto
coffee:prime-server Steven$ ko apply -f grpc-service.yaml
2019/07/03 15:10:55 Error enumerating files: lstat grpc-service.yaml: no such file or directory
coffee:prime-server Steven$ error: no objects passed to apply

**Comment by vagababov** [comment]
/close
this is not a really supported code
But it's obvious the file name is spelled differently
